#!/usr/bin/env python3
"""Write mltk-container/local/images.conf so DSDL/AITK resolve the DEFAULT Splunk
images from ECR instead of Docker Hub (airgapped environment).

Per the DSDL Container Customization docs, DSDL builds the image reference it pulls
by concatenating the stanza's `repo` + `image`. The app ships these stanzas in
mltk-container/default/images.conf with `repo = splunk/`; a stanza of the same name
in local/ overrides default/ (standard Splunk .conf layering). This script emits a
local/images.conf that keeps each default stanza's title/runtime but repoints
`repo`/`image` at the shared ECR repository (one tag per image).

Inputs (env):
  ECR_REGISTRY_URI     e.g. 123456789012.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY_NAME  e.g. splunk-ai-containers-ab12c
  DSDL_IMAGES_MANIFEST path to dsdl-default-images.json (default: alongside this script)
  IMAGES_CONF_PATH     output path (required)
"""

import json
import os
import sys
from pathlib import Path


def main():
    registry = os.environ.get("ECR_REGISTRY_URI", "").strip()
    repo_name = os.environ.get("ECR_REPOSITORY_NAME", "").strip()
    out_path = os.environ.get("IMAGES_CONF_PATH", "").strip()
    manifest_path = os.environ.get(
        "DSDL_IMAGES_MANIFEST",
        str(Path(__file__).resolve().parent / "dsdl-default-images.json"),
    )

    if not out_path:
        print("ERROR: IMAGES_CONF_PATH not set", file=sys.stderr)
        sys.exit(1)
    if not registry or not repo_name:
        print("ERROR: ECR_REGISTRY_URI and ECR_REPOSITORY_NAME must be set", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(Path(manifest_path).read_text())
    images = manifest.get("images", [])
    if not images:
        print("ERROR: manifest has no images", file=sys.stderr)
        sys.exit(1)

    # DSDL pull ref = repo + image. Point repo at the registry and put the shared
    # ECR repo name + per-image tag in `image`, e.g.:
    #   repo  = 123.dkr.ecr.ap-southeast-1.amazonaws.com/
    #   image = splunk-ai-containers-ab12c:mltk-container-golden-cpu-5.2.4
    repo_field = f"{registry}/"

    lines = [
        "# Generated by generate_default_images_conf.py for the airgapped environment.",
        "# Overrides mltk-container/default/images.conf to pull default DSDL images from ECR.",
        "",
    ]
    for img in images:
        lines += [
            f"[{img['stanza']}]",
            f"title = {img['title']}",
            f"repo = {repo_field}",
            f"image = {repo_name}:{img['ecr_tag']}",
            f"runtime = {img['runtime']}",
            "",
        ]

    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(images)} ECR-backed default image stanza(s) to {out_path}")


if __name__ == "__main__":
    main()
